In [1]:
# Import

import numpy as np

In [10]:
# Temperature/Apple problem

w1, w2, w3 = 0.3, 0.2, 0.5

In [4]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

kanto_apples = kanto_temp*w1+kanto_rainfall*w2+kanto_humidity*w3
print(apples)

56.8


In [5]:
Kanto = [73, 67, 43]
Johto = [91, 88, 64]
Hoenn = [87, 134, 58]
Sinnoh = [102, 43, 37]
Unova = [69, 96, 70]

weights = [w1, w2, w3]

In [7]:
def crop_yield(region,weights):
    result = 0
    for x, w in zip(region, weights):
        result += x*w
    return result

In [8]:
crop_yield(Kanto,weights)

56.8

In [9]:
crop_yield(Johto,weights)

76.9

In [12]:
# Numpy's use in previous problem
# np.array()

kanto = np.array([73, 67, 43])
weights = np.array([w1, w2, w3])

In [13]:
type(kanto)
type(weights)

numpy.ndarray

In [15]:
# help() is a good way to learn functions
# np.dot() works like the crop_yield function 

np.dot(kanto,weights)

np.float64(56.8)

In [16]:
(kanto*weights).sum()

np.float64(56.8)

In [19]:
# 2 dimensional numpy array using previous data [temp, rainfall, hum]

climate_data = np.array([[73, 67, 43], 
                         [91, 88, 64], 
                         [87, 134, 58], 
                         [102, 43, 37], 
                         [69, 96, 70]])

In [20]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [24]:
# 1 dimensional array is a vector (4,). 2 dimensional array (2,3), 3 dimensional array (4,3,2)

climate_data.shape

# 5 rows by 3 columns

(5, 3)

In [25]:
weights

array([0.3, 0.2, 0.5])

In [26]:
weights.shape

(3,)

In [32]:
# 3 dimensional

arr3 = np.array([[[11,12,13],
                  [13,14,15]],

                 [[15,16,17],
                  [17,18,19.5]]])

In [33]:
arr3.shape

(2, 2, 3)

In [34]:
# All elements in an array needs the same data type and should be the same length

climate_data.dtype

dtype('int64')

In [35]:
# Matrix multiplication np.matmul()

np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [36]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [54]:
# Importing CSV with 10,000 accounts of temp, rainfall, and humidity

new_climate_data = np.genfromtxt(r"C:\Users\ewlem\Documents\Portfolio Projects\Python\Learning\environment_data.csv", delimiter=',', skip_header=1, usecols=(1,2,3))


In [55]:
new_climate_data

array([[ 44.94,  74.73,  75.7 ],
       [114.09,  66.58,  26.61],
       [ 87.84,  35.23,  41.2 ],
       ...,
       [113.6 ,  60.74,  11.75],
       [ 47.7 ,  88.66,  46.09],
       [ 26.06,  34.45,  33.17]])

In [56]:
new_climate_data.shape

(10000, 3)

In [57]:
weights

array([0.3, 0.2, 0.5])

In [58]:
yields = new_climate_data @ weights

In [59]:
yields

array([66.278, 60.848, 53.998, ..., 52.103, 55.087, 31.293])

In [60]:
yields.shape

(10000,)

In [61]:
# Adding apple yields as a new column to the original data

climate_results = np.concatenate((new_climate_data, yields.reshape(10000,1)),axis=1)

In [62]:
climate_results

array([[ 44.94 ,  74.73 ,  75.7  ,  66.278],
       [114.09 ,  66.58 ,  26.61 ,  60.848],
       [ 87.84 ,  35.23 ,  41.2  ,  53.998],
       ...,
       [113.6  ,  60.74 ,  11.75 ,  52.103],
       [ 47.7  ,  88.66 ,  46.09 ,  55.087],
       [ 26.06 ,  34.45 ,  33.17 ,  31.293]])

In [63]:
climate_results.shape

(10000, 4)

In [64]:
# Save file
# np.savetxt("", climate_results, fmt="%.2f", header="temperature,rainfall,humidity,apple_yield")

In [65]:
# Numpy functions
# Mathematics: np.sum, np.exp, np.round
# Array: np.reshape, np.stack, np.concatenate, np.split
# Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
# Statistics: np.mean, np.median, np.std, np.max

In [68]:
# Arrays can also be added and more
# arr2 + arr3 will make an array with the sum of each number in each position in the arrays
# Even arrays that aren't the same like (3,4) and (4,) can be added. 
# The (4,) will be distributed to each of the other lines so it will be added like (3,4) + (4,4)
# However the shapes need to match...
# You can't add an array like this:

In [69]:
# Arr3 = np.array([7,8])
# Arr4 = np.array([[4,2,3,1], [3,4,7,6]])

In [70]:
arr1 = np.array([[1,2,3],[1,2,3],[1,2,3]])
arr2 = np.array([[2,1,3],[2,1,3],[2,1,3]])
arr1==arr2

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [71]:
(arr1==arr2).dtype

dtype('bool')

In [73]:
# Number of matching elemets = 3
(arr1==arr2).sum()

np.int64(3)

In [74]:
arr3 = np.array([
    [[11,12,13,14],
     [13,14,15,19]],

    [[15,16,17,21],
     [63,92,36,18]],

    [[98,32,81,23],
     [17,18,19.5,43]]])

In [75]:
arr3.shape

(3, 2, 4)

In [76]:
# 3 arrays 2 rows, 4 columns

In [77]:
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [78]:
arr3[1][1]

array([63., 92., 36., 18.])

In [79]:
arr3[1][1][0]

np.float64(63.0)

In [81]:
# Subarray using ranges

arr3[1:, 0:1, :2]

# Starting from the 2nd array, show me rows starting at the first row but not the 2nd row, show me columns that go up to the 3rd column

array([[[15., 16.]],

       [[98., 32.]]])

In [83]:
# Mixing indices and ranges

arr3[1:, 1, 3]

# Exclude the first array (start from 2nd array), show me row position index 1 (2nd row) and column position index 3 (4th column)

array([18., 43.])

In [84]:
# : will show all

In [86]:
# Creating an array

In [87]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [88]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [89]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [95]:
# rand is 0 to 1
# randn is around 0 but not tied to 0 to 1, picked from a probability distribution

np.random.rand(4)

array([0.018254  , 0.87150956, 0.66596918, 0.38111341])

In [96]:
np.random.randn(3,2)

array([[ 0.54392776, -0.39069584],
       [ 1.14523921, -1.46514917],
       [-0.49943053,  0.56649784]])

In [98]:
# A 2 by 3 matrix with number 42

np.full((2,3), 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [99]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [100]:
# Creates an array that starts at 10 goes to 90 and each number increases by 3

In [101]:
np.arange(10,90,3).shape

(27,)

In [102]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [103]:
# reshape makes it a (3,3,3) array, a 3 dimensional array

In [104]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [105]:
# linspace makes a range from 3 to 27 with 9 steps that are equally spaced out